FROM python:3.10

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

ARG BSKY_USERNAME
ARG BSKY_PASSWORD
ENV BSKY_USERNAME=$BSKY_USERNAME
ENV BSKY_PASSWORD=$BSKY_PASSWORD

CMD ["python","-u","main.py"]
